# Generated by Django 4.1.2 on 2022-10-27 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='officemodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('DateofJoining', models.DateField(default=datetime.datetime.now)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('Working', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
            ],
        ),
    ]
